# -*- coding: utf-8 -*-
"""Gen-AI3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_hV5qUPYbH5_Zs94G8uIR_iz4A54k90
"""

# ✅ AUTO-INSTALL (if missing)
try:
    from transformers import pipeline
except ImportError:
    import os
    os.system('pip install transformers torch')

# ✅ IMPORTS
from transformers import pipeline

# ✅ LOAD GPT-2 PIPELINE
generator = pipeline("text-generation", model="gpt2")

# ✅ FUNCTION TO GENERATE ANIME CONCEPT
def generate_anime_concept(user_idea):
    prompt = f"""
Create a detailed anime concept from the following idea: "{user_idea}"

Include:
1. Title
2. Genre
3. Main Character
4. Setting
5. Plot/Synopsis

Anime Concept:
"""
    result = generator(prompt, max_length=250, temperature=0.8, num_return_sequences=1)[0]['generated_text']
    return result.strip()

# ✅ USER INPUT
user_input = input("💡 Enter your anime idea (e.g. fire user in cyberpunk world):\n> ")
concept = generate_anime_concept(user_input)

# ✅ OUTPUT RESULT
print("\n🎬 Generated Anime Concept:\n")
print(concept)